### ISSUE TITLE
"An unexpected error occurred while attempting to execute this command" when using the command

### ISSUE THREAD

**Issue by WinExp** [BlossomMods/BlossomEnderChest#2]
When I tried to use the /echest command, it said "An unexpected error occurred while attempting to execute this command".
No error logs on the server side.
![image](https://github.com/BlossomMods/BlossomEnderChest/assets/55543397/df8d8cc0-2a2a-4933-b3ba-f9f9ef30dba6)

**Comment by CodedSakura** [comment]
this is caused by a mistake i made in the default config. the default color name is set to `purple`, which is not a valid color name in minecraft. it should be `light_purple`
